question_data = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Linux was first created as an alternative to Windows XP.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "A Mac is not a PC",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "JavaScript derives from a later version of Java",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Ada Lovelace is often considered the first computer programmer.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The Windows 7 operating system has six main editions.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The Windows ME operating system was released in the year 2000.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Time on Computers is measured via the EPOX System.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The logo for Snapchat is a Bell.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The first IBM PC was released in 1981.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "An average human can go two weeks without water.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Sports",
        "question": "Peyton Manning retired after winning Super Bowl XLIX.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "An Astronomical Unit is the distance between Earth and the Moon.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Vehicles",
        "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Sports",
        "question": "There are a total of 20 races in Formula One 2016 season.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Politics",
        "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was &quot;Yes We Can&quot;.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In Chobits, Hideki found Chii in his apartment.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In &quot;Sonic Adventure&quot;, you are able to transform into Super Sonic at will after completing the main story.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "Bulls are attracted to the color red.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Politics",
        "question": "Denmark has a monarch.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Art",
        "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "Kangaroos keep food in their pouches next to their children.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "Zebras are white with black stripes.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Animals",
        "question": "Rabbits are carnivores.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "The main antagonist in the videogame Saints Row IV is an entity known as The Mastermind.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Music",
        "question": "Eurobeat is primarily an Italian genre of music.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "Rhode Island is actually located on the US mainland, despite its name.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "An atom contains a nucleus.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Sports",
        "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "The United States was a member of the League of Nations.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "History",
        "question": "The United States of America declared their independence from the British Empire on July 4th, 1776.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Politics",
        "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Time on Computers is measured via the EPOX System.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Television",
        "question": "In the Season 1 SpongeBob Squarepants episode, &quot;Help Wanted,&quot; the song &quot;Living in the Sunlight&quot; by Tiny Tim can be heard.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In the Monster Hunter Series, G-Rank is the highest possible prestige a Hunter can recieve.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Film",
        "question": "The film &quot;2001: A Space Odyssey&quot; was released on December 31st, 2000.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "General Knowledge",
        "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Vehicles",
        "question": "BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "California is larger than Japan.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Gadgets",
        "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Japanese Anime &amp; Manga",
        "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science &amp; Nature",
        "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Geography",
        "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Mythology",
        "question": "In the Greek Mythology, the god of war is called Mars.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Board Games",
        "question": "There is a Donald Trump Board Game, which was made in 1989.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "Nintendo&#039;s Luigi was originally just called Green Mario?",
        "correct_answer": "False",
        "incorrect_answers": "True",
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Books",
        "question": "The book 1984 was published in 1949.",
        "correct_answer": "True",
        "incorrect_answers": "False",
    },
]
